In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_excel("/Users/stone/Desktop/필요/4_2/BigData/팀플/응급실+내원사유+현황_20231003161942.xlsx")

In [10]:
df.head(20)

,연령별(1),연령별(2),성별(1),2021,2021.1,2021.2,2021.3,2021.4,2021.5,2021.6,2021.7,2021.8,2021.9,2021.10,2021.11,2021.12,2021.13,2021.14,2021.15,2021.16
0,연령별(1),연령별(2),성별(1),계,계,계,계,계,계,계,계,계,계,계,계,계,계,계,계,계
1,연령별(1),연령별(2),성별(1),소계,질병,질병외: 손상기전,질병외: 손상기전,질병외: 손상기전,질병외: 손상기전,질병외: 손상기전,질병외: 손상기전,질병외: 손상기전,질병외: 손상기전,질병외: 손상기전,질병외: 손상기전,질병외: 손상기전,질병외: 손상기전,질병외: 손상기전,진료외방문,미상/미입력
2,연령별(1),연령별(2),성별(1),소계,소계,소계,교통사고,추락,미끄러짐,부딪힘,베임찔림,기계,화상,익수,중독,질식,기타,미상/미입력,소계,소계
3,합계,소계,계,1157022,838285,269238,32679,20799,56086,47772,40381,1871,5767,235,6442,635,54776,1795,49196,303
4,NaN,NaN,남자,558077,397270,140441,21177,11440,26646,28702,20673,1487,2464,145,2199,324,24094,1090,20183,183
5,NaN,NaN,여자,598945,441015,128797,11502,9359,29440,19070,19708,384,3303,90,4243,311,30682,705,29013,120
6,NaN,1세미만,계,15083,10646,4211,60,2028,256,713,210,3,150,5,66,12,653,55,224,2
7,NaN,1 - 9세,계,87744,46143,39304,1605,5161,7778,12477,3372,58,904,15,297,30,7222,385,2285,12
8,NaN,10 - 19세,계,60479,38805,19235,2958,931,2896,4615,2643,34,448,27,756,34,3797,96,2431,8
9,NaN,20 - 29세,계,159900,105357,45111,6661,1552,4867,6314,10172,221,1213,64,1972,120,11754,201,9408,24
10,NaN,30 - 39세,계,143318,98970,33763,5422,1234,4091,5466,7055,189,796,37,862,93,8379,139,10548,37
11,NaN,40 - 49세,계,128995,93680,28761,4400,1384,4248,4712,5672,257,699,24,732,79,6408,146,6520,34
12,NaN,50 - 59세,계,153332,113750,32324,4610,2093,6563,5053,5405,497,753,24,684,92,6328,222,7210,48
13,NaN,60 - 69세,계,170485,134350,29554,3923,2413,7798,4064,3914,447,532,21,517,69,5645,211,6533,48
14,NaN,70 - 79세,계,138492,115165,20477,2196,2154,8456,2489,1464,129,180,10,314,56,2864,165,2807,43
15,NaN,80세이상,계,99194,81419,16498,844,1849,9133,1869,474,36,92,8,242,50,1726,175,1230,47
16,NaN,연령미상,계,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-

In [7]:
df1 = df.transpose()	#행 열 전환

In [9]:
df1.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
연령별(1),연령별(1),연령별(1),연령별(1),합계,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
연령별(2),연령별(2),연령별(2),연령별(2),소계,NaN,NaN,1세미만,1 - 9세,10 - 19세,20 - 29세,30 - 39세,40 - 49세,50 - 59세,60 - 69세,70 - 79세,80세이상,연령미상
성별(1),성별(1),성별(1),성별(1),계,남자,여자,계,계,계,계,계,계,계,계,계,계,계
2021,계,소계,소계,1157022,558077,598945,15083,87744,60479,159900,143318,128995,153332,170485,138492,99194,-
2021.1,계,질병,소계,838285,397270,441015,10646,46143,38805,105357,98970,93680,113750,134350,115165,81419,-
2021.2,계,질병외: 손상기전,소계,269238,140441,128797,4211,39304,19235,45111,33763,28761,32324,29554,20477,16498,-
2021.3,계,질병외: 손상기전,교통사고,32679,21177,11502,60,1605,2958,6661,5422,4400,4610,3923,2196,844,-
2021.4,계,질병외: 손상기전,추락,20799,11440,9359,2028,5161,931,1552,1234,1384,2093,2413,2154,1849,-
2021.5,계,질병외: 손상기전,미끄러짐,56086,26646,29440,256,7778,2896,4867,4091,4248,6563,7798,8456,9133,-
2021.6,계,질병외: 손상기전,부딪힘,47772,28702,19070,713,12477,4615,6314,5466,4712,5053,4064,2489,1869,-